# .streamlit/secrets.toml
type = "service_account"
project_id = "pipe-analysis"
private_key_id = "8a30b74f205a96ff05de705cecfe8f15ee560c3c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCR9YT4tkyTk/pM
wQljXmdfZdX28VBZyKW27Bz8y1Bev0F+XEbB/ii79qbsv4THFB+pxubI8j23DPIq
/C44SMLNRjRyVlnYRdzx1NXEHKbD4D02y655Yd347SQg4ivxhlkwe5SlrO7hGDjs
nFBM5QnJn/jTDoZouNn3Ah2vO5qZjJadOYx4ajHQVimaGEYb92dp62Myl1tRXKt/
pyG94rkFaris0JCh/1QTnlRFpRbY0S92Gufkk7tDh2oUC2WPYXm+Qel+8l/dGQhv
EcEtwqTZ1YkEATSDadVL3Fley7cPcCGSMWa6TaFKxHgf0/S54wj1xPg/Ox/mR/b0
qISo83RRAgMBAAECggEABKi9seK/1wYmO0T+M7nTuuvZRKS3V+Zbw9cNpdQnoJ6i
TJJNf+vJCRb6hRwn9OLjj9vVihyRc8JqCI08PHe2IC9ZhTzUaV7xipasrDHt8Nq7
mYAu9Zj2KPgI6zPNC0yqlC2dtRwsE+teBc+HkKzO/yyoGLSh/b3I12Wt5OYWLUiP
PvaOVCk5C8uP+9TnaWWyyOz8zQ/fWBCMCO1ceQ2TtPRczbnSkRAkveUrA0ZmHxnK
evEv422/8yllGTkCIs6Tu7QpAspgE8MQTDfH4vxb1JFoSQAq2UdvKJTidbOdM8Nb
zTBxKKo5TcTqptunIYyLzzk7zOCTp+4RkD0dvYubQQKBgQDBm2PxgX/c2461+LqK
6Dwq7ISkuRxN63UBG9dV8yKPFFoQbOdkv7q2PNYCXox1QwnwfntiAoACkPZ4LBOd
a29u6W1k+Z2HuPVhUrdscvstxw3J75hWU36rcayIu7s6i0SMOBzZ6MZZXcrHiMgm
/kOsG++I4CU3qtl9H2uQu4ysvQKBgQDA/yqeDvR2myEN5FEY5r8hP0PHhh/1a8rG
HC0dutYY/UsuHNYLttygCXSB0WLcoQwR2FY+V9eXTRQYQUkdVUvL5fmhh11N2F/a
Gt/yforp/Rdth99XZvNuYMoeo0zTuHn0PqOudRdwEG+al0Dp+dOSO5pTs7hZuvnL
yKxQHTTBJQKBgQCrATNvtzBWxV7x//XUh3fNegdW72G+uUApcIvskMpvkkxSwb5I
UMj7+hQVF6n8UPBQiYc1dHvYyG3KizPwEVrlnixPyeKIZKfoBIWatpyBPJZDTOtD
JJB3ofoA88BV33j2WQGyv1WizaM0Ru5y8paXSD10qnZ1CuT7DWuW9PE2CQKBgQCQ
NltXDh+3/MUfR0seC1Yodsij7+Izlh9IF8fSnkjbFXI2+88po7OKVmZbluWDrUeC
kiAnp6XuZectFKOYqqLfsnHtNGQRBizhohFTdyFAJSF7c/r8qW4fPW3qpOWEkyV1
z9SpSM+BqpZqcrlL3KUucSEpiHKpgiCkGMhBeQFxjQKBgQCPxpMdpUuKp1ghVNkm
NvDuYIPF9fyw9VetOk8ioRG5G6202Y9QbvxpLzE+MgjcBbEfsCqGSePpJkGYRQhb
m1N+7Q5ro19fuUHbI7Pb6oF3PlffmnD/UH6TH4wOn4GJLnsPBBNMv9BeGmbawb+u
5LUAC3z+jHFdnDUFxkdUFGRleA==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@pipe-analysis.iam.gserviceaccount.com"
client_id = "110640662917146007934"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40pipe-analysis.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
