type = "service_account"
project_id = "pipe-analysis"
private_key_id = "fb4e698f96e75b97a9b5d9cf2332874973dcd76f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqu2+Awsewvs5x
mFTUJTKVk/W7tkvqW6daVwEpUI1xt8qkxnIN4HULWqvUZuuc4mo/HOgY+5GcEI4W
+wDGC3ydk1x1GYuFyaXb9DfkN14hKAOSQ4XBZA7xfPCEo2k72pX/7T/r3uBBEW+D
N3oIS/KwCWtTp2Wr2KddbaPMSM2GdQKq3kcFzrPQIyBjnCPgJVVFhFVMe9zofSEz
fSnDIaIyr/rMYcYRigY1TFn+GOD+NmJQ8jWFweAnCTS4bJfKrdXLnqkaWnEbSmHr
AxeqUi8EtoTOnDlaLI+6qzReU9YCtF+KWr6Z+JGYEkLiSNVO1JWxh7Z++jkt3Jkd
D0ZJi7OFAgMBAAECggEAB+c+0WFS4J/oixIf5SUmqw1rG+ojqADfpZsu8tRng8rb
/tYv2+wWxvSGzUGJaR0DCZJjPRrSIf0TMsWiQsiv11SFvGb3EjWkL6MlvjMA8Lx7
M9db1vi0h2G++Yjd+3cSKAN5yMerrl9p/9M+2yj23kbFWN1AI90W3EiRw0hgeTeY
g5iM+CsBoRMp9MKVmM8AoMjt8XYxXL9B7tqUemxsIOk64HNQidTGv16w2EcK7soq
GsMNFl3lzC7MV6x+TFAc+D9YEppzcS4DADtsf3Um+Hxz2ik9HN4D8t1zbaZyjkvS
7EGMSfTD0wI5aOo5Hzmtn+zt2BCtUZ490BfJuN28oQKBgQDhdNwHPGBuzLCCgSld
U/qMPdmcRVK/bmQZywBDbhGMvzEDeBxkJSSumpYiGigEdtYyvS9vCSsvnXJ55fYv
cZ5rvyMivy6bHeTQZQAW7ywW5QANQcWUt9gdOzz2fx/zPNnc0xbYBWHa8Y8lBiUy
RZVhUox0ySpxvcXco3CoN5FGpQKBgQDB3KlojAW2vDPwGiNsqp8SYKqDftkMsIlU
MC56naQ3LTdMwLWdO6tPniJxnJqKOfH32QboNHvXc+pEj27rwAmL+58WNteITaZc
MXyEfE/vBGZhDV5k1LJBcEVlaxnLNYvDB+WI1FYYBxCCSUdZalj5tyMa+nozzeBm
FG9FxTwDYQKBgHdiGOyf9PRW4RSJ7mxj/qTqT2OndbS2cL0TuHT8QMDFsN+EZ4xD
+tOWOe+e6BfNEYlWklp6gWq6NZcExULEKD4nvSQ2Fii/QJ11DgIW7cLFyiw66rPg
UcjQyGxCTpnPXBHJmSwUVYfJJ6JUSbgADqS1QHjK2PXXpoE57nq0yfGdAoGAUHD5
srH3ZP3vJ0ARVvPtkbieyHWIJuXR9icQAj0LeQHAIo8MTTQHP8BEVpQ+5ABrUQaz
AQNWJ+6nVM+XnSdQTs+YEaWsBZkC4Np/6pGSsYFH4hmkA37mgJTPlue8CkArwD+0
lPRWzR2RUh6KBqZESUoevQEWWAyjgngUPAU9g8ECgYEA3hn6kR+86rjgOErFDoB5
JLgaUchD4wLrtYELC391R3dfHBDnsswuR/MTyXWS/jaQc3lO8xrTucujjnOFHkbA
sx52ccxHCni5GGLoGw+mvspv1srx+cs+aK6gpLIMTOLtmZ6O6LAvWySNweTz2PQA
z9cUEwH8iILRzpDpgQklKGc=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@pipe-analysis.iam.gserviceaccount.com"
client_id = "110640662917146007934"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40pipe-analysis.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
